import type { NextPage } from 'next'
import Head from 'next/head'
// import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { getPosts } from '../lib/posts';

export async function getStaticProps(context:any) {
  const posts = await getPosts()

  if (!posts) {
    return {
      notFound: true,
    }
  }

  return {
    props: { posts }
  }
}

const Home: NextPage = (props:any) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Blog de Withney Guilherme</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">my blog</a>
        </h1>


        <div className={styles.grid}>
          {
          props?.posts?.map((post:any)=>{
            return (
              <a  key={post.id} href="#" className={styles.card}>
              <h2>Documentation &rarr;</h2>
              <p>Find in-depth information about Next.js features and API.</p>
            </a>
            )
          })
          }
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="#"
          target="_blank"
          rel="noopener noreferrer"
        >
          Desenvolvido por<strong style={{marginLeft: '5px'}}>Withney Guilherme</strong>
        </a>
      </footer>
    </div>
  )
}

export default Home
